import Head from 'next/head'
import Image from 'next/image'
import Carousel from '../components/Carousel';
import Hero from '../components/Hero';

export async function getServerSideProps() {
  const maxPageNum = 2

  async function fetchFinalData(maxPages, fetchUrl) {
    const randomPage = Math.floor(Math.random() * maxPages) + 1;
    const res = await fetch(`${fetchUrl}&page=${randomPage}`)
    const data = await res.json();

    return data;
  }

  async function fetchData(maxPages, fetchUrl) {
    const res = await fetch(fetchUrl)
    const data = await res.json();
    let result = null;
    if (data.total_pages >= maxPages) {
      result = await fetchFinalData(maxPages, fetchUrl);
    } else {
      result = await fetchFinalData(1, fetchUrl);
    }
    return result;
  }

  async function fetchRandom(fetchUrl) {
    const resHero = await fetch(fetchUrl)
    const random_trending = await resHero.json();
    let tempMov = random_trending.results;
    let movieID = tempMov[Math.floor(Math.random() * tempMov.length)].id;

    const randomMovieRes = await fetch(`https://api.themoviedb.org/3/movie/${movieID}?api_key=${process.env.API_KEY}&language=en-US`)
    const data = await randomMovieRes.json();

    const movieVideosRes = await fetch(`https://api.themoviedb.org/3/movie/${movieID}/videos?api_key=${process.env.API_KEY}&language=en-US`)
    const trailer = await movieVideosRes.json();

    return {data, trailer}
  }

  // Fetch data from external API
  const trending = await fetchData(maxPageNum, `https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.API_KEY}`)
  const top_rated = await fetchData(maxPageNum, `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US`)
  const upcoming = await fetchData(maxPageNum, `https://api.themoviedb.org/3/movie/upcoming?api_key=${process.env.API_KEY}&language=en-US`)
  const randomMovie = await fetchRandom(`https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.API_KEY}`)

  // Pass data to the page via props
  return {
    props: {
      data: { trending, top_rated, upcoming, randomMovie },
    },
  };
}

export default function Home({ data }) {
  //console.log(data)
  return (
    <div >
      <Head>
        <title>Home | MovieSpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero movie={data.randomMovie} h={75}/>
      <Carousel title={"Trending"} data={data.trending} cardHeight={400} cardWidth={270}/>
      <Carousel title={"Top Rated"} data={data.top_rated} cardHeight={400} cardWidth={270}/>
      <Carousel title={"Upcoming"} data={data.upcoming} cardHeight={400} cardWidth={270}/>

    </div>
  )
}
