import Head from 'next/head'

export default function watchlist() {
    return (
        <Head>
            <title>Watchlist | MovieSpot</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}
